# Generated by Django 4.2 on 2026-03-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parrainages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusparrainage',
            name='filleul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_parrain', to=settings.AUTH_USER_MODEL, verbose_name='Filleul'),
        ),
        migrations.AlterField(
            model_name='bonusparrainage',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant du bonus'),
        ),
        migrations.AlterField(
            model_name='bonusparrainage',
            name='parrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_parrainages', to=settings.AUTH_USER_MODEL, verbose_name='Parrain'),
        ),
    ]
