# Generated by Django 4.2 on 2026-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='categorie_achat',
            field=models.CharField(default='AUCUN', max_length=12, verbose_name='CATEG'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('AUCUN', '------------'), ('TRNSPRT', 'TRANSPORT'), ('AGRCL', 'AGRICOL')], default='AUCUN', max_length=12, verbose_name='CATEG'),
        ),
    ]
