# Generated by Django 4.2 on 2026-03-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_achat_categorie_achat_alter_produit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='categorie_achat',
        ),
    ]
