# Generated by Django 4.2 on 2026-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_remove_achat_categorie_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gainquotidien',
            name='poste_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de posting'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('AUCUN', '------------'), ('TRNSPRT', 'TRANSPORT'), ('AGRCL', 'AGRICOL'), ('ENERGIE', 'ÉNERGIE'), ('IMMOBILIER', 'IMMOBILIER LOCATIF'), ('COMMERCE', 'COMMERCE'), ('INDUSTRIE', 'INDUSTRIE')], default='AUCUN', max_length=12, verbose_name='CATEG'),
        ),
    ]
