# Generated by Django 4.2 on 2025-09-16 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        default="", max_length=100, verbose_name="Nom complet"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        default="", max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=200, verbose_name="Titre de la requête"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_traite", "Non traité"),
                            ("en_cours", "En cours de traitement"),
                            ("traite", "Traité"),
                        ],
                        default="non_traite",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "date_fermeture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fermeture"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Catégorie"
                    ),
                ),
                (
                    "assigne_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requetes_assignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requête",
                "verbose_name_plural": "Requêtes",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Reponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "est_interne",
                    models.BooleanField(
                        default=False,
                        verbose_name="Note interne (non visible par le client)",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "requete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="service_client.requete",
                        verbose_name="Requête",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
                "ordering": ["date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="pieces_jointes/", verbose_name="Fichier"
                    ),
                ),
                (
                    "nom_original",
                    models.CharField(max_length=255, verbose_name="Nom original"),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "requete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_jointes",
                        to="service_client.requete",
                        verbose_name="Requête",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
            },
        ),
    ]
