# Generated by Django 4.2 on 2025-11-26 00:00

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portefeuille", "0004_alter_transactionportefeuille_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectifPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intitule",
                    models.CharField(
                        max_length=200, verbose_name="Intitulé de l'objectif"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "periodicite",
                    models.CharField(
                        choices=[
                            ("journalier", "Journalier"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("semestriel", "Semestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="mensuel",
                        max_length=15,
                        verbose_name="Périodicité",
                    ),
                ),
                (
                    "nombre_filleuls_requis",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de filleuls requis"
                    ),
                ),
                (
                    "filleuls_doivent_acheter",
                    models.BooleanField(
                        default=True,
                        verbose_name="Les filleuls doivent effectuer un achat",
                    ),
                ),
                (
                    "prime_objectif",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Prime pour objectif atteint",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Objectif actif"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "produits_eligibles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Produits que les filleuls doivent acheter (laisser vide pour tous les produits)",
                        related_name="objectifs_personnel",
                        to="produits.produit",
                        verbose_name="Produits éligibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif personnel",
                "verbose_name_plural": "Objectifs du personnel",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Matricule du personnel",
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        default="Collaborateur",
                        max_length=100,
                        verbose_name="Poste occupé",
                    ),
                ),
                (
                    "date_embauche",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Salaire de base",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("congé", "En congé"),
                        ],
                        default="actif",
                        max_length=10,
                        verbose_name="Statut professionnel",
                    ),
                ),
                (
                    "telephone_pro",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone professionnel",
                    ),
                ),
                (
                    "email_pro",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email professionnel",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre du personnel",
                "verbose_name_plural": "Membres du personnel",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PrimePersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_prime",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant de la prime",
                    ),
                ),
                (
                    "nombre_filleuls_qualifies",
                    models.PositiveIntegerField(
                        verbose_name="Nombre de filleuls qualifiés"
                    ),
                ),
                (
                    "date_versement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de versement"
                    ),
                ),
                (
                    "objectif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_bonana.objectifpersonnel",
                        verbose_name="Objectif",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primes",
                        to="gestion_bonana.personnel",
                        verbose_name="Membre du personnel",
                    ),
                ),
                (
                    "transaction_associee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portefeuille.transactionportefeuille",
                        verbose_name="Transaction associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prime du personnel",
                "verbose_name_plural": "Primes du personnel",
                "ordering": ["-date_versement"],
            },
        ),
        migrations.CreateModel(
            name="PostulerObjectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("accepte", "Accepté"),
                            ("rejete", "Rejeté"),
                        ],
                        default="accepte",
                        max_length=20,
                        verbose_name="Statut de la candidature",
                    ),
                ),
                (
                    "date_postulation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de postulation"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "objectif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulations",
                        to="gestion_bonana.objectifpersonnel",
                        verbose_name="Objectif",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulations",
                        to="gestion_bonana.personnel",
                        verbose_name="Personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postulation à un objectif",
                "verbose_name_plural": "Postulations aux objectifs",
                "ordering": ["-date_postulation"],
                "unique_together": {("personnel", "objectif")},
            },
        ),
        migrations.CreateModel(
            name="PerformancePersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_filleuls_parraines",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de filleuls parrainés"
                    ),
                ),
                (
                    "nombre_filleuls_qualifies",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de filleuls qualifiés"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("atteint", "Objectif atteint"),
                            ("non_atteint", "Objectif non atteint"),
                            ("prime_payee", "Prime payée"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut de performance",
                    ),
                ),
                (
                    "prime_recue",
                    models.BooleanField(default=False, verbose_name="Prime reçue"),
                ),
                (
                    "date_prime",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de versement de la prime",
                    ),
                ),
                (
                    "date_debut_suivi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Début du suivi"
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "postulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="gestion_bonana.postulerobjectif",
                        verbose_name="Postulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance du personnel",
                "verbose_name_plural": "Performances du personnel",
                "ordering": ["-date_debut_suivi"],
            },
        ),
        migrations.CreateModel(
            name="FilleulPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "est_eligible",
                    models.BooleanField(
                        default=False, verbose_name="Est éligible pour l'objectif"
                    ),
                ),
                (
                    "date_parrainage",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de parrainage"
                    ),
                ),
                (
                    "date_qualification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de qualification"
                    ),
                ),
                (
                    "montant_achat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Montant du contrat",
                    ),
                ),
                (
                    "achat_filleul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parrainages_personnel",
                        to="produits.achat",
                        verbose_name="Achat du filleul",
                    ),
                ),
                (
                    "filleul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parrainages_personnel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Filleul parrainé",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filleuls",
                        to="gestion_bonana.performancepersonnel",
                        verbose_name="Performance",
                    ),
                ),
                (
                    "produit_achete",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.produit",
                        verbose_name="Produit acheté",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filleul du personnel",
                "verbose_name_plural": "Filleuls du personnel",
                "unique_together": {("performance", "filleul", "achat_filleul")},
            },
        ),
    ]
